/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.deepcode.javaclient;

import ai.deepcode.javaclient.responses.LoginResponse;
import org.junit.Test;
import static org.junit.Assert.*;

public class DeepCodeRestApiTest {

  @Test
  public void newLogin() {
    LoginResponse response = DeepCodeRestApi.newLogin();
    assertNotNull(response);
    assertEquals(
        "https://www.deepcode.ai/login-api?sessionToken=" + response.sessionToken,
        response.loginURL);
    //    System.out.println(response.loginURL);
  }

  @Test
  public void checkSession() {
    int status = DeepCodeRestApi.checkSession("");
    assertEquals(401, status);

    status = DeepCodeRestApi.checkSession("blablabla");
    assertEquals(401, status);

    LoginResponse response = DeepCodeRestApi.newLogin();
    assertNotNull(response);
    status = DeepCodeRestApi.checkSession(response.sessionToken);
    assertEquals(304, status);

    // !!! Will works only with already logged sessionToken
    //    status =
    // DeepCodeRestApi.checkSession("aeedc7d1c2656ea4b0adb1e215999f588b457cedf415c832a0209c9429c7636e");
    //    assertEquals(200, status);

  }
}
