/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.deepcode.javaclient;

import ai.deepcode.javaclient.responses.LoginResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import retrofit2.Call;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;
import retrofit2.http.GET;
import retrofit2.http.Header;
import retrofit2.http.POST;

import java.io.IOException;

/**
 * https://deepcode.freshdesk.com/support/solutions/articles/60000346777-sessions
 * https://deepcode.freshdesk.com/support/solutions/articles/60000357438-bundles
 */
public final class DeepCodeRestApi {

  private static final Logger LOGGER = LoggerFactory.getLogger(DeepCodeRestApi.class);

  private DeepCodeRestApi() {}

  private static String API_URL = "https://www.deepcode.ai/publicapi/";

  private static final Gson lenientGson = new GsonBuilder().setLenient().create();

  // Create simple REST adapter which points the API_URL.
  private static final Retrofit retrofit =
      new Retrofit.Builder()
          .baseUrl(API_URL)
          .addConverterFactory(GsonConverterFactory.create(lenientGson))
          .build();

  private interface LoginCall {
    @retrofit2.http.Headers("Content-Type: application/json")
    @POST("login")
    Call<LoginResponse> doNewLogin();
  }

  /** Requests the creation of a new login session. */
  // todo: Status Code checks, error handling
  public static LoginResponse newLogin() {
    LoginCall loginCall = retrofit.create(LoginCall.class);
    LoginResponse loginResponse = null;
    try {
      loginResponse = loginCall.doNewLogin().execute().body();
    } catch (IOException e) {
      final String msg = "Error while requesting new login: ";
      LOGGER.error(msg, e);
      throw new RuntimeException(msg, e);
    }
    return loginResponse;
  }

  private interface CheckSessionCall {
    @GET("session")
    Call<String> doCheckSession(@Header("Session-Token") String token);
  }

  /**
   * Checks status of the login process.
   *
   * @return Status Code
   */
  // todo: error handling
  public static int checkSession(String token) {
    CheckSessionCall checkSessionCall = retrofit.create(CheckSessionCall.class);
    int statusCode = 0;
    try {
      Call<String> call = checkSessionCall.doCheckSession(token);
      Response<String> response = call.execute();
      statusCode = response.code();
    } catch (IOException e) {
      final String msg = "Error while checking login session status: ";
      LOGGER.error(msg, e);
      throw new RuntimeException(msg, e);
    }
    /*    String text;
        switch (status) {
          case 200:
            text = "The login process was successful";
            break;
          case 304:
            text = "The login process has not been completed yet";
            break;
          case 401:
            text = "Missing or invalid sessionToken";
            break;
          default:
            text = "Unknown Status Code: " + status;
            LOGGER.error(text);
            break;
        }
    */
    return statusCode;
  }
}
